FROM n8nio/n8n

ENV GENERIC_TIMEZONE=${GENERIC_TIMEZONE}

# 設定基本驗證（需搭配 .env）
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=${BASIC_AUTH_USER}
ENV N8N_BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
