services:
  - type: web
    name: n8n-auto
    env: docker
    plan: free
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Taipei
      - key: BASIC_AUTH_USER
        value: admin
      - key: BASIC_AUTH_PASSWORD
        value: password123
